# docker-compose.prod.yml
# Production configuration for Bank RAG system
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  laravel:
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
    # Remove development volumes
    volumes: []
    # Add production optimizations
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  postgres:
    # Don't expose PostgreSQL port in production
    ports: []
    # Production database configuration
    environment:
      - POSTGRES_DB=bankrag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_SECURE_PASSWORD_HERE
    # Add production optimizations
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  python-flask:
    # Remove development volumes
    volumes: []
    environment:
      - FLASK_ENV=production
    # Add production optimizations
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  llama:
    # Production memory limits
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

# Production networks (optional)
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16